//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranTienPhat_2122110302.DB
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class Brand
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Show { get; set; }
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
