//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranTienPhat_2122110302.DB
{
    using System.Web;
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> isadmin { get; set; }
        public string image { get; set; }
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
